version: '3.1'

services:
  server:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "node out/index.js"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: database.dockerfile
    ports:
      - "5433:5432"
  testdata: 
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../ccims-testdata/:/home/node/app
    command: "node dist/index.js"
    depends_on:
      - db
